GovernmentService-war/src/java/fit5042/mbeans/PublicUserManagedBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fit5042.mbeans;

import fit5042.repository.PublicUserRepository;
import fit5042.repository.ServiceUseRepository;
import fit5042.repository.entities.PublicUser;
import fit5042.repository.entities.ServiceUse;
import fit5042.utility.Constant;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 *
 * @author Ivan Zhu <ivanzhujunwei@gmail.com>
 */
@ManagedBean(name = "publicUserBean")
@SessionScoped
public class PublicUserManagedBean 
{

    @EJB
    PublicUserRepository publicUserRepository;
    
    @EJB
    ServiceUseRepository serviceUseRepository;

    // The variable to judge if this request is showing all public users search page  by worker
    private boolean isShowAll;

    private String userName;

    private String password;

    // Login result after use attempts to login
    private String loginResponse;

    // Search ID number in search page
    private String searchID;
    // Search first name in search page
    private String searchLastName;
    // Search first name in search page
    private String searchFirstName;
    // Search email in search page
    private String searchEmail;

    // The public user the worker is managing
    private PublicUser user;
    
    // Search active and inactive public user
    public String activeSelect;

    public PublicUserManagedBean()
    {
        user = new PublicUser();
        isShowAll = true;
        searchID = "";
        searchLastName = "";
        searchFirstName = "";
        searchEmail = "";
        activeSelect = "1";
    }

    
    /**
     * *
     * Public user login
     *
     * @param userName
     * @param password
     * @return true if userName and password are both correct
     */
//    public String login() throws IOException
//    {
//        // THIS IS AJAX HERE, NEED VIEWSCOPE 
//        if (Validate.isEmpty(userName)) {
//            setLoginResponse("ddd");
//            return "login";
//        }
//        for (PublicUser pu : publicUserRepository.getAllPublicUser()) {
//            if (userName.equals(pu.getEmail()) && password.equals(pu.getPassword())) {
//                // Load user's data 
//                this.loginResponse = "";
//                ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
//                context.redirect(context.getRequestContextPath() + "/faces/publicUser/index.xhtml");
//            }
//        }
//        setLoginResponse("Login failed");
//        return "login";
//    }
    
//    public String loginJASS(){
//        return "worker/worker_publicUsers";
//    }

    /**
     * *
     * Search public user, set isShowAll false
     *
     */
    public void getSearchedServices()
    {
        isShowAll = false;
    }

    /**
     * *
     * Show All public users
     */
    public void getShowAllPublicUser()
    {
        isShowAll = true;
        activeSelect = "1";
    }

    /**
     * *
     * Get public users according isShowAll attribute
     *
     * @return
     */
    public List<PublicUser> getAllPublicUsers()
    {
        List<PublicUser> users = new ArrayList<>();
        // Show all users when the page is initialised
        if (isShowAll) {
            users = getPublicUserList();
        } else {
            boolean isActive = activeSelect.equals("1");
            users = publicUserRepository.getSearchPublicUserCombined(searchID, searchLastName, searchFirstName, searchEmail, isActive);
        }
        return users;
    }

    /**
     * *
     * Get all public users
     *
     * @return PublicUser list
     */
    public List<PublicUser> getPublicUserList()
    {
        try {
            return publicUserRepository.getAllPublicUser();
        } catch (Exception ex) {
            Logger.getLogger(ServiceManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    /***
     * Go to adding public user page
     * @return Adding public user page
     */
    public String addingPublicUser()
    {
        this.user = new PublicUser();
        int id = publicUserRepository.getNewPublicUserId();
        this.user.setId(id);
        
        return "worker_publicUser_add";
    }
    
    /***
     * Add a user 
     * @return User manage home page
     */
    public String addPublicUser(){
            user.setPassword(SHA(user.getPassword()));
            user.setUser_type("public");
            publicUserRepository.addPublicUser(user);
        return "worker_publicUsers";
    }
    
    // reference: blog.csdn.net/joyous/article/details/49898383
    private String SHA(final String strText)
    {
        // 返回值  
        String strResult = null;
        // 是否是有效字符串  
        if (strText != null && strText.length() > 0) {
            try {
                // SHA 加密开始  
                // 创建加密对象 并傳入加密類型  
                MessageDigest messageDigest = MessageDigest.getInstance("SHA-256");
                // 传入要加密的字符串  
                messageDigest.update(strText.getBytes());
                // 得到 byte 類型结果  
                byte byteBuffer[] = messageDigest.digest();
                // 將 byte 轉換爲 string  
                StringBuffer strHexString = new StringBuffer();
                // 遍歷 byte buffer  
                for (int i = 0; i < byteBuffer.length; i++) {
                    String hex = Integer.toHexString(0xff & byteBuffer[i]);
                    if (hex.length() == 1) {
                        strHexString.append('0');
                    }
                    strHexString.append(hex);
                }
                // 得到返回結果  
                strResult = strHexString.toString();
            } catch (NoSuchAlgorithmException e) {
                e.printStackTrace();
            }
        }
  
    return strResult;  
  }  

    
    
    public String updatePublicUser(){
        publicUserRepository.updatePublicUser(this.user);
        return "worker_publicUsers";
    }
    
    /***
     * Get the public user detail
     * @param p Public user
     * @return  public user detail page
     */
    public String getViewedUser(PublicUser p){
        this.user = p;
        return "worker_publicUser_detail";
    }

    /***
     * Get to the updating user page
     * @param p Public user
     * @return public user update page
     */
    public String getUpdatingUser(PublicUser p){
        this.user = p;
        return "worker_publicUser_update";
    }
    
    /***
     * Delete a user 
     * @param p The public user needed to be deleted
     * @return 
     */
    public String deleteUser(PublicUser p){
        // delete all his/her service use records
        for (ServiceUse su :serviceUseRepository.getServiceUseByUser(p)){
            serviceUseRepository.deleteServiceUse(su);
        }
        // delete the public user
        publicUserRepository.deletePublicUser(p);
        return "worker_publicUsers";
    }
    
    public String activePublicUser(PublicUser p){
        p.setIsActive(true);
        publicUserRepository.updatePublicUser(p);
        return "worker_publicUsers";
    }
    
    public String inactivePublicUser(PublicUser p){
        // set service status
        p.setIsActive(false);
        // status of related service use remain
        publicUserRepository.updatePublicUser(p);
        return "worker_publicUsers";
    }

    /***
     * Reset user's password
     */
    public void resetPassword(){
        this.user.setPassword(SHA(Constant.DEFAULT_PSD));
        publicUserRepository.updatePublicUser(user);
    }
    
    
    /**
     * *
     * Get current service use records
     *
     * @return Service use list
     */
    public List<ServiceUse> getCurrentServiceUse()
    {
        System.out.println("fit5042.mbeans.LoginManagedBean.getCurrentServiceUse()");
        List<ServiceUse> sus = new ArrayList<>();
        for (ServiceUse su : getAllServiceUse()) {
            if (!su.isIsFinished()) {
                sus.add(su);
            }
        }
        return sus;
    }

    /**
     * *
     * Get completed service use records
     *
     * @return Service use list
     */
    public List<ServiceUse> getFinishedServiceUsesByPublic()
    {
        List<ServiceUse> sus = new ArrayList<>();
        for (ServiceUse su : getAllServiceUse()) {
            if (su.isIsFinished()) {
                sus.add(su);
            }
        }
        return sus;
    }

    /***
     * Get all service use
     * @return 
     */
    public List<ServiceUse> getAllServiceUse()
    {
        return serviceUseRepository.getServiceUseByUser(user);
    }
    public String getUserName()
    {
        return userName;
    }

    public String getPassword()
    {
        return password;
    }

    public void setUserName(String userName)
    {
        this.userName = userName;
    }

    public void setPassword(String password)
    {
        this.password = password;
    }

    public String getLoginResponse()
    {
        return loginResponse;
    }

    public void setLoginResponse(String loginResponse)
    {
        this.loginResponse = loginResponse;
    }

    public String getSearchID()
    {
        return searchID;
    }

    public String getSearchLastName()
    {
        return searchLastName;
    }

    public String getSearchFirstName()
    {
        return searchFirstName;
    }

    public String getSearchEmail()
    {
        return searchEmail;
    }

    public void setSearchID(String searchID)
    {
        this.searchID = searchID;
    }

    public void setSearchLastName(String searchLastName)
    {

GovernmentService-war/web/includes/worker/worker_publicUser_add.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"      
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:body>
        <ui:composition template="/layout/workerTemplete.xhtml">
            <ui:define name="content">
                <div class="container"> 
                    <!-- /.row -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <a href="worker_publicUsers.xhtml">User Manage</a> / Add a user </div>
                        <div class="panel-body">
                            <h:form enctype="multipart/form-data">
                                <div class="col-lg-9 col-md-9 col-sm-9 service-attribute">
                                    <div class="form-group col-lg-12 col-md-12 h5">
                                        <label class="col-lg-2 control-label">ID number:</label>
                                        <div class="col-lg-6 service-update-attribute">
                                            <h:inputText class="form-control" disabled="true" value="#{publicUserBean.user.id}"/>
                                        </div>
                                    </div>
                                    <div class="form-group col-lg-12 col-md-12 h5">
                                        <label class="col-lg-2 control-label">Last name:</label>
                                        <div class="col-lg-6 service-update-attribute">
                                            <h:inputText id="lastName" class="form-control" value="#{publicUserBean.user.lastName}"
                                                         required="true" requiredMessage="You must enter the last name" 
                                                         validatorMessage="Numbers are not allowed here">
                                                <f:validateRegex pattern="(^[^\d()]+$)"/>
                                            </h:inputText>
                                        </div>
                                        <label class="col-lg-4 control-label validate-error"><h:message for="lastName"/></label>
                                    </div>
                                    <div class="form-group col-lg-12 col-md-12 h5">
                                        <label class="col-lg-2 control-label">First name:</label>
                                        <div class="col-lg-6 service-update-attribute">
                                            <h:inputText id="firstName" class="form-control" value="#{publicUserBean.user.firstName}"
                                                         required="true" requiredMessage="You must enter the first name" 
                                                         validatorMessage="Numbers are not allowed here">
                                                <f:validateRegex pattern="([^\d()]+)"/>
                                            </h:inputText>
                                        </div>
                                        <label class="col-lg-4 control-label validate-error"><h:message for="firstName"/></label>
                                    </div>
                                    <div class="form-group col-lg-12 col-md-12 h5">
                                        <label class="col-lg-2 control-label">Email:</label>
                                        <div class="col-lg-6 service-update-attribute">
                                            <h:inputText id="email" class="form-control" value="#{publicUserBean.user.email}"
                                                         required="true" requiredMessage="You must enter an email" 
                                                         validatorMessage="Incorrect email">
                                                <f:validateRegex pattern="[\w\.-]*[a-zA-Z0-9_]@[\w\.-]*[a-zA-Z0-9]\.[a-zA-Z][a-zA-Z\.]*[a-zA-Z]" />
                                            </h:inputText>
                                        </div>
                                        <label class="col-lg-4 control-label validate-error"><h:message for="email"/></label>
                                    </div>
                                    <div class="form-group col-lg-12 col-md-12 h5">
                                        <label class="col-lg-2 control-label">Phone:</label>
                                        <div class="col-lg-6 service-update-attribute">
                                            <h:inputText id="phone" class="form-control" value="#{publicUserBean.user.phone}"
                                                         required="true" requiredMessage="You must enter a phone" 
                                                         validatorMessage="Incorrect phone">
                                                <f:validateRegex pattern="[9][0-9]{7}|[0][0-9]{9}"></f:validateRegex>
                                            </h:inputText>
                                        </div>
                                        <label class="col-lg-4 control-label validate-error"><h:message for="phone"/></label>
                                    </div>
                                    <div class="form-group col-lg-12 col-md-12 h5">
                                        <label class="col-lg-2 control-label">Address:</label>
                                        <div class="col-lg-6 service-update-attribute">
                                            <h:inputText class="form-control" value="#{publicUserBean.user.address}"/>
                                        </div>
                                    </div>
                                    <div class="form-group col-lg-12 col-md-12 h5">
                                        <label class="col-lg-2 control-label">Password</label>
                                        <div class="col-lg-6 service-update-attribute">
                                            <h:inputText class="form-control" disabled="true" value="#{publicUserBean.user.password}"/>
                                        </div>
                                    </div>
                                    <div class="form-group col-lg-12 col-md-12 h5">
                                        <div class="col-lg-3 col-md-3 col-sm-3 ">
                                            <h:commandButton class="btn btn-sm btn-success" value="Add the public user" action="#{publicUserBean.addPublicUser()}"></h:commandButton>
                                        </div>
                                    </div>
                                </div>
                            </h:form>
                        </div>
                    </div> 
                </div>
            </ui:define> 

        </ui:composition>

    </h:body>
</html>

GovernmentService-war/web/includes/worker/worker_publicUsers.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"      
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough">
    <h:body>
        <ui:composition template="/layout/workerTemplete.xhtml">
            <ui:define name="content">
                <!--<h:link value="Back To Home" outcome="service_detail" />-->
                <div class="container"> 
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-sm-4">
                            <h:form id="searchForm">
                                <div class="col-lg-12 col-md-12 smart-margin-bottom-30 findAService">
                                    <h1 class="agent-page-header">
                                        User management  
                                    </h1>
                                </div>
                                <h:outputText id="activeOrnotId" class="hidden" value="#{publicUserBean.activeSelect}"></h:outputText>
                                <div class="col-lg-12 col-md-12 smart-margin-bottom-30">
                                    <div class="col-lg-12  smart-margin-bottom-10">
                                        <h:inputText class="form-control"  p:placeholder="ID Number." value="#{publicUserBean.searchID}">
                                        </h:inputText>
                                    </div>
                                    <div class="col-lg-12  smart-margin-bottom-10">
                                        <h:inputText class="form-control"  p:placeholder="Last name" value="#{publicUserBean.searchLastName}">
                                        </h:inputText>
                                    </div>
                                    <div class="col-lg-12  smart-margin-bottom-10">
                                        <h:inputText class="form-control"  p:placeholder="First name" value="#{publicUserBean.searchFirstName}">
                                        </h:inputText>
                                    </div>
                                    <div class="col-lg-12 smart-margin-bottom-10">
                                        <h:inputText class="form-control"  p:placeholder="Email" value="#{publicUserBean.searchEmail}">
                                        </h:inputText>
                                    </div>
                                    <div class="col-lg-12 ">
                                        <h:selectOneMenu class="form-control" style="height:35px" value="#{publicUserBean.activeSelect}">
                                            <f:selectItem itemValue="1" itemLabel="Active public users" />
                                            <f:selectItem itemValue="0" itemLabel="Inactive public users" />
                                        </h:selectOneMenu>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="col-lg-6">
                                        <h:commandLink class="btn btn-block btn-success smart-margin-bottom-20" value="Show all" action="#{publicUserBean.getShowAllPublicUser}">
                                        </h:commandLink>
                                    </div>
                                    <div class="col-lg-6">
                                        <h:commandLink class="btn btn-block btn-success" value="Search" action="#{publicUserBean.getSearchedServices}">
                                            &nbsp;&nbsp;<i class="fa fa-search"></i>
                                        </h:commandLink>
                                    </div>
                                </div>
                            </h:form>
                        </div>
                        <!--START  //Service table with NO and name-->
                        <div class="col-lg-8">
                            <h:form>
                                <div class="userManageBtn">
                                    <div class="col-lg-9"></div>
                                    <div class="col-lg-3">
                                        <h:commandLink class="btn btn-block btn-success smart-margin-bottom-20" value="Add user" action="#{publicUserBean.addingPublicUser}">
                                            &nbsp;&nbsp;<i class="fa fa-user-plus"></i>
                                        </h:commandLink>
                                    </div>
                                </div>

                                <table class="table table-striped">
                                    <tr>
                                        <th width="15%"> ID </th>
                                        <th width="20%"> Last Name </th>
                                        <th width="20%"> First Name </th>
                                        <th width="20%"> Email </th>
                                        <th width="10%"> Actions </th>
                                        <th width="3%">  </th>
                                        <th width="3%">  </th>
                                        <th width="3%">  </th>
                                    </tr>
                                    <!-- For each service in service list... --> 
                                    <ui:repeat id="Myrepeat" value="#{publicUserBean.allPublicUsers}" var="p" varStatus="status"> 
                                        <tr> 
                                            <td style="vertical-align: middle">  <h:outputText value="#{p.id}" />  </td>
                                            <td style="vertical-align: middle">  <h:outputText value="#{p.lastName}" />  </td>
                                            <td style="vertical-align: middle"> <h:outputText value="#{p.firstName}"  /></td>
                                            <td style="vertical-align: middle"> <h:outputText value="#{p.email}"  /></td>
                                            <td style="vertical-align: middle">  <h:outputText />
                                                <h:commandLink action="#{publicUserBean.getViewedUser(p)}">
                                                    <i class="fa fa-eye"></i>
                                                </h:commandLink>&nbsp;&nbsp;&nbsp;&nbsp;
                                                <h:commandLink action="#{publicUserBean.getUpdatingUser(p)}">
                                                    <i class="fa fa-pencil"></i>
                                                </h:commandLink>&nbsp;&nbsp;&nbsp;&nbsp;
                                            </td>
                                            <td>
                                                <h:commandLink action="#{publicUserBean.inactivePublicUser(p)}"
                                                               onclick="if (!confirm('Really inactivate this public user?')) {
                                                                           return false;
                                                                       }
                                                                       ;
                                                                       return true;">
                                                    <i class="fa fa-trash" aria-hidden="true"></i>
                                                </h:commandLink>
                                            </td>
                                            <td>
                                                <h:commandLink action="#{publicUserBean.activePublicUser(p)}"
                                                               onclick="if (!confirm('Really activate this public user?')) {
                                                                           return false;
                                                                       }
                                                                       ;
                                                                       return true;">
                                                    <i class="fa fa-undo" aria-hidden="true"></i>
                                                </h:commandLink>
                                            </td>
                                            <td>
                                                <h:commandLink action="#{publicUserBean.deleteUser(p)}"
                                                               onclick="if (!confirm('All the service use records will be removed, really delete this public user?')) {
                                                                           return false;
                                                                       }
                                                                       ;
                                                                       return true;">
                                                    <i class="fa fa-remove"></i>
                                                </h:commandLink>
                                            </td>
                                        </tr> 
                                    </ui:repeat> 

                                </table>
                            </h:form>
                        </div>
                        <!--END  //Service table with NO and name-->
                    </div>
                </div> 
                <script type="text/javascript">
                    $(document).ready(function () {
                        var activeOrNot = $("#searchForm\\:activeOrnotId").text();
                        if (activeOrNot === "0") {
                            $("tr").css("color", "grey");
                            $("td:nth-child(6)").hide();
                        }else {
                            $("td:nth-child(7)").hide();
                            $("td:nth-child(8)").hide();
                        }
                    });
                </script>
            </ui:define> 

        </ui:composition>

    </h:body>
</html>